// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.oneprofiles.domain;

import com.oneprofiles.domain.Role;

privileged aspect Role_Roo_JavaBean {
    
    public String Role.getRole() {
        return this.role;
    }
    
    public void Role.setRole(String role) {
        this.role = role;
    }
    
}
